services:
  task-manager:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 14022014
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
